config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users

  resources :users, only: [:show] do
    resources :items, only: [:new, :create]
  end
  resources :items, only: [:destroy]
  root to: 'users#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  default_scope { order(created_at: :asc) }
  validates :name, length: { minimum: 3 }, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :items

  attr_accessor :login

  validates :username,
  :presence => true,
  :uniqueness => {
    :case_sensitive => false
  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def new
    @item = Item.new
    @user = current_user
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user

    if @item.save
      redirect_to root_path, notice: "Item was saved successfully."
    else
      flash.now[:alert] = "Error creating item. Please try again."
      render :new
    end
  end

  def destroy
     @item = Item.find(params[:id])
     @item.destroy

    respond_to do |format|
      format.html
      format.js
    end
  end

  private
  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    if user_signed_in?
      @user = current_user
      @items = Item.where(:user => @user)
      @item = Item.new
    else
      render :template => "welcome/index"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if user_signed_in?
      @user = current_user
      @items = Item.where(:user => @user)
    else
      render :template => "welcome/index"
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?
    content_tag :div, capture(&block), class: css_class
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<h2>New Item</h2>
  <div class="new-item-container">
    <%= form_for [@user, Item.new], :remote => true do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter to-do item" %>
       </div>
        <div class="form-group">
          <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
    <% end %>
  </div>

app/views/items/_item.html.erb
<li class="list-group-item">
  <span class="badge"> <%= distance_of_time_in_words(item.created_at, Time.now - 10.days)  %>  </span><%= item.name %><span> <%= link_to "", item, remote: true, method: :delete, class: 'glyphicon glyphicon-ok' %>
</li>

app/views/items/create.js.erb
$("#to-do-list").append("<li id="to-do-item" class="<%= 'list-group-item-danger' if distance_of_time_in_words(item.created_at, Time.now - 10.days).split(" ").first.to_i <= 3 %> list-group-item ">
  <span class="badge"> <%= distance_of_time_in_words(item.created_at, Time.now - 10.days) + " left"  %>  </span><%= item.name %><span> <%= link_to "", item, remote: true, method: :delete, class: 'glyphicon glyphicon-ok' %>
</li>");

app/views/items/destroy.js.erb
$('.glyphicon').bind('ajax:success', function() {
   $(this).closest('li').fadeOut();
});

app/views/items/new.html.erb
<div class='container'>
  <div class="row">
    <h1>New Item</h1>
    <%= form_for [@user, @item] do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter to-do item" %>
       </div>
        <div class="form-group">
          <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>Blocitoff</title>
      <%= csrf_meta_tags %>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>
      <div class="row">
        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/users/show">Blocitoff</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Home", root_path %></li>
                <% if user_signed_in? %>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
                <% else %>
                <li><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %></li>
                <li><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
    </body>
  </html>

app/views/user/show.html.erb
<div class="container">
<div class="row">
<h1><%= @user.username %> <small><%= link_to 'Edit profile', edit_user_registration_path, :class => 'link' %></small></h1>
<p> Last log in occured on <%= @user.last_sign_in_at %></p>
<h2> My To-Do Lists <small> <%= link_to "New Item", new_user_item_path(@user, @item), class: 'btn btn-primary' %></small> </h2>
<div class="col">
  <% @items.each do |item| %>
    <ul class="list-group">
        <li class="list-group-item">
          <span class="badge"> Time left </span><%= item.name %>
        </li>
    </ul>
  <% end %>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-md-6 col-lg-6">
      <h1><%= @user.username %> <small><%= link_to 'Edit profile', edit_user_registration_path, :class => 'link' %></small></h1>
      <p> Last log in occured on <%= @user.last_sign_in_at %></p>
    </div>
    <div class="col-sm-6 col-md-6 col-lg-6">
      <%= render 'items/form', review: Item.new(user_id: @user.id) %>
    </div>
  </div>
  <div class="row">
    <h2> My To-Do List</h2>
      <div class="list-container">
        <ul id='to-do-list' class="list-group">
          <%= render partial: 'items/item', collection: @items || "Lets start a To-Do List!"%>
        </ul>
      </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Blocitoff</h1>
    <p>Blocitoff creates handy To-Do complete with expiration dates!</p>
    <button type="button" class="btn btn-default btn-lg"><%= link_to "Sign Up", new_user_registration_path, :class => 'button-link'  %></button>
    <button type="button" class="btn btn-default btn-lg"><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %></button>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h2>Make life easier with your own To-Do List.</h2>
      <p>The days of missing trash pickup are over!</p>
    </div>
    <div class="col-md-6">
      <h2>Challenge yourself to do more with your day.</h2>
      <p>Set a time limit or expiration date for each of your list items.</p>
    </div>
  </div>
</div>